#
#   ▄▄▄▄   ▓█████▄▄▄█████▓▄▄▄█████▓▓█████  ██▀███       ██████ ▓█████  ▄████▄   █    ██  ██▀███   ██▓▄▄▄█████▓▓██   ██▓
#  ▓█████▄ ▓█   ▀▓  ██▒ ▓▒▓  ██▒ ▓▒▓█   ▀ ▓██ ▒ ██▒   ▒██    ▒ ▓█   ▀ ▒██▀ ▀█   ██  ▓██▒▓██ ▒ ██▒▓██▒▓  ██▒ ▓▒ ▒██  ██▒
#  ▒██▒ ▄██▒███  ▒ ▓██░ ▒░▒ ▓██░ ▒░▒███   ▓██ ░▄█ ▒   ░ ▓██▄   ▒███   ▒▓█    ▄ ▓██  ▒██░▓██ ░▄█ ▒▒██▒▒ ▓██░ ▒░  ▒██ ██░
#  ▒██░█▀  ▒▓█  ▄░ ▓██▓ ░ ░ ▓██▓ ░ ▒▓█  ▄ ▒██▀▀█▄       ▒   ██▒▒▓█  ▄ ▒▓▓▄ ▄██▒▓▓█  ░██░▒██▀▀█▄  ░██░░ ▓██▓ ░   ░ ▐██▓░
#  ░▓█  ▀█▓░▒████▒ ▒██▒ ░   ▒██▒ ░ ░▒████▒░██▓ ▒██▒   ▒██████▒▒░▒████▒▒ ▓███▀ ░▒▒█████▓ ░██▓ ▒██▒░██░  ▒██▒ ░   ░ ██▒▓░
#  ░▒▓███▀▒░░ ▒░ ░ ▒ ░░     ▒ ░░   ░░ ▒░ ░░ ▒▓ ░▒▓░   ▒ ▒▓▒ ▒ ░░░ ▒░ ░░ ░▒ ▒  ░░▒▓▒ ▒ ▒ ░ ▒▓ ░▒▓░░▓    ▒ ░░      ██▒▒▒
#  ▒░▒   ░  ░ ░  ░   ░        ░     ░ ░  ░  ░▒ ░ ▒░   ░ ░▒  ░ ░ ░ ░  ░  ░  ▒   ░░▒░ ░ ░   ░▒ ░ ▒░ ▒ ░    ░     ▓██ ░▒░
#   ░    ░    ░    ░        ░         ░     ░░   ░    ░  ░  ░     ░   ░         ░░░ ░ ░   ░░   ░  ▒ ░  ░       ▒ ▒ ░░
#   ░         ░  ░                    ░  ░   ░              ░     ░  ░░ ░         ░        ░      ░            ░ ░
#        ░                                                            ░                                        ░ ░
#
#   Version: ${project.version} | BungeeCord Version
#   Modules -> commands.yml
#
#   Do you need help?
#   -> https://docs.kyotoresources.space
#
# Function of the executors:
#
# - [MESSAGE] text                                         | (Func. Send a chat message) | (Example: [MESSAGE] &aHello World!)
#
# - [MINI_MESSAGE] mini format message                     | (Func. Send a chat message with the MiniMessage format)
#                                                          | (Tip. To use this format read this page: https://docs.adventure.kyori.net/minimessage/index.html)
#                                                          | (Example: [MINI_MESSAGE] <green>Hello World!)
#
# - [TITLE] title;subtitle;fade-in;stay;fade-out           | (Func. Submit a title)
#                                                          | (Tip. If you enter "none" in the title or subtitle, it will not be displayed)
#                                                          | (Example: [TITLE] &a&lHELLO WORLD;&a&l┃ &aThis is a fantastic world!;1;2;1)
#
# - [ACTION] text                                          | (Func. Send a message in the action bar) | (Example: [ACTION] &aHello World!)
#
# - [PLAYER] command without '/'                           | (Func. Send a command as a player) | (Example: [PLAYER] spawn)
#
# - [CONSOLE] command without '/'                          | (Func. Send a command from the console) | (Example: [CONSOLE] give %player% DIAMOND 1)
#
# - [KICK] reason                                          | (Func. Kick the player for a reason) | (Example: [KICK] &cYou got kicked, because you don't have cookies.)
#
# If you put an "@" in front of the text, it will broadcast the execution.
# Works for the following performers: [MESSAGE], [TITLE], [ACTION], [BOSSBAR], [SOUND]
# Examples: [MESSAGE] @&aHello World! | [TITLE] @&a&lHELLO WORLD;&a&l┃ &aThis is a fantastic world!;20;40;20
# | [ACTION] @&aHello World! | [BOSSBAR] @&aHello World!;GREEN;SEGMENTED_20;1.0;5 | [SOUND] @BLOCK_LAVA_POP;0;1
#
# If you don't want to do anything, just put "[]" after "executors:"
# Example: executors: []
#
# You can use the following placeholders in all executors:
# - %prefix% | (Plugin prefix: Settings > Prefix)
# - %player% | (Name of the player who attempted to execute the command)
# - %server% | (Server name)
# - %command% | (The command that was blocked)
# - %center% | (You can center text, only works with messages)


# If it is on "true" the execution attempt warning will be sent to chat.
warning: true

# Here you can enter the type of method you want to use to block commands:
# - BLACKLIST | (The commands in the list will be blocked)
# - WHITELIST | (The commands in the list will be able to execute)
method: 'BLACKLIST'

# Forced checking if enabled can cause problems with other plugins.
# For example AuthMeBungee (If you execute a blocked command before login, the plugin will overwrite it)
force_check: false

# This message will be shown as soon as the command is blocked.
# < ? > You can find more information about the executors in the header.
executors:
  - '[MESSAGE] %prefix%&cYou cannot execute this command!'

# List of blocked or enabled commands according to the selected method.
# If you want to block commands only through "server mode", just put "commands: []"
commands:
  - 'bungee'
  - 'waterfall'
  - 'pl'
  - 'plugins'
  - 'ver'
  - 'version'
  - 'about'
  - '?'
  - 'help'
  - 'bukkit:pl'
  - 'bukkit:plugins'
  - 'bukkit:ver'
  - 'bukkit:version'
  - 'bukkit:about'
  - 'bukkit:?'
  - 'bukkit:help'
  - 'minecraft:?'
  - 'minecraft:help'

# Server mode allows you to block commands based on the server the player is on.
server_mode:

  enabled: false

  # This is the list of servers where commands are blocked.
  servers:
    # This is an example server.
    lobby:
      # < ? > The methods are the same that are located above.
      method: 'BLACKLIST'
      # Instead these are the commands blocked on that server.
      commands:
        - 'examplecommand1'
        - 'examplecommand2'
    # In this example you can use another message.
    survival:
      # < ? > The methods are the same that are located above.
      method: 'BLACKLIST'
      # This executor will only be sent to this server.
      # < ? > You can find more information about the executors in the header.
      executors:
        - '[MESSAGE] &a&lSURVIVAL ┃ &cYou cannot execute this command!'
      # Instead these are the commands blocked on that server.
      commands:
        - 'examplecommand1'
        - 'examplecommand2'


#    ____                                _   _             _  __           _        ____
#   |  _ \ _____      _____ _ __ ___  __| | | |__  _   _  | |/ /   _  ___ | |_ ___ |  _ \ ___  ___  ___  _   _ _ __ ___ ___  ___
#   | |_) / _ \ \ /\ / / _ \ '__/ _ \/ _` | | '_ \| | | | | ' / | | |/ _ \| __/ _ \| |_) / _ \/ __|/ _ \| | | | '__/ __/ _ \/ __|
#   |  __/ (_) \ V  V /  __/ | |  __/ (_| | | |_) | |_| | | . \ |_| | (_) | || (_) |  _ <  __/\__ \ (_) | |_| | | | (_|  __/\__ \
#   |_|   \___/ \_/\_/ \___|_|  \___|\__,_| |_.__/ \__, | |_|\_\__, |\___/ \__\___/|_| \_\___||___/\___/ \__,_|_|  \___\___||___/
#                                                  |___/       |___/